#!/bin/bash
#SBATCH --partition=bsudfq
#SBATCH --nodes=4
#SBATCH --ntasks=192
#SBATCH --time=20-00:00:00
#SBATCH --job-name=scotia3
#SBATCH --output=scotia3.out

# Load modules
module load slurm
module load gdal/gcc8/3.0.4
module load R/gcc8/4.0.2

cd /bsuhome/bkerswell/scratch/kerswell_kohn_backarc-cluster-3

# Define list of nodes for parallel computing
export NODES=$(scontrol show hostnames $SLURM_NODELIST)

Rscript cluster_ga.R Scotia 10
